[tools]
remodel = { source = "rojo-rbx/remodel", version = "0.10.0" }
rojo = { source = "rojo-rbx/rojo", version = "7.1.1" }
run-in-roblox = { source = "rojo-rbx/run-in-roblox", version="0.3.0" }
selene = { source = "Kampfkarren/selene", version = "0.17.0" }
wally = { source = "UpliftGames/wally", version = "0.3.1"}