[package]
name = "chipioindustries/dragon-game"
description = "A game about fighting dragons"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Flipper = "reselim/flipper@2.0.0"
LeakyBucket = "chipioindustries/leaky-bucket@1.0.1"
Llama = "chipioindustries/llama@1.2.2"
Maid = "flamenco687/maid@3.2.2"
Roact = "roblox/roact@1.4.2"
RoactRodux = "chipioindustries/roact-rodux@1.0.4"
Remotes = "chipioindustries/remotes@1.0.1"
ReplicationMiddleware = "chipioindustries/replication-middleware@1.0.0"
Rodux = "chipioindustries/rodux@3.0.4"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"